/**
 * Get categorized domains for display
 * @returns {Object} Object containing categorized domains
 */

export function getCategorizedDomains() {
  const categories = {
    "🔧 开发平台": {
      GitHub: "github.com",
      GitLab: "gitlab.com",
      Gitea: "gitea.com",
      Codeberg: "codeberg.org",
      SourceForge: "sourceforge.net",
      "Android 源码": "android.googlesource.com",
      "Hugging Face": "huggingface.co",
      Civitai: "civitai.com",
    },
    "📦 包管理器": {
      NPM: "registry.npmjs.org",
      PyPI: "pypi.org",
      "Python 托管": "files.pythonhosted.org",
      Conda: "repo.anaconda.com",
      "Conda 社区": "conda.anaconda.org",
      "Maven 中央": "repo1.maven.org",
      Apache: "downloads.apache.org",
      "Gradle 插件": "plugins.gradle.org",
      Homebrew: "github.com/Homebrew",
      "Homebrew API": "formulae.brew.sh/api",
      "Homebrew 镜像": "ghcr.io",
      RubyGems: "rubygems.org",
      CRAN: "cran.r-project.org",
      CPAN: "www.cpan.org",
      CTAN: "tug.ctan.org",
      "Go 模块": "proxy.golang.org",
      NuGet: "api.nuget.org",
      "Crates.io": "crates.io",
      Packagist: "repo.packagist.org",
    },
    "🐧 Linux 发行版": {
      Debian: "deb.debian.org",
      Ubuntu: "archive.ubuntu.com",
      Fedora: "dl.fedoraproject.org",
      "Rocky Linux": "download.rockylinux.org",
      openSUSE: "download.opensuse.org",
      "Arch Linux": "geo.mirror.pkgbuild.com",
    },
    "🤖 AI 推理服务": {
      OpenAI: "api.openai.com",
      Anthropic: "api.anthropic.com",
      Gemini: "generativelanguage.googleapis.com",
      "Vertex AI": "aiplatform.googleapis.com",
      Cohere: "api.cohere.ai",
      "Mistral AI": "api.mistral.ai",
      xAI: "api.x.ai",
      "GitHub Models": "models.github.ai",
      "NVIDIA API": "integrate.api.nvidia.com",
      Perplexity: "api.perplexity.ai",
      Braintrust: "api.braintrust.dev",
      Groq: "api.groq.com",
      Cerebras: "api.cerebras.ai",
      SambaNova: "api.sambanova.ai",
      Siray: "api.siray.ai",
      "Hugging Face 推理": "router.huggingface.co",
      Together: "api.together.xyz",
      Replicate: "api.replicate.com",
      "Fireworks AI": "api.fireworks.ai",
      "Nebius AI": "api.studio.nebius.ai",
      "Jina AI": "api.jina.ai",
      VoyageAI: "api.voyageai.com",
      "Fal.ai": "fal.run",
      "Novita AI": "api.novita.ai",
      "BurnCloud AI": "ai.burncloud.com",
      OpenRouter: "openrouter.ai",
      Poe: "api.poe.com",
      "Featherless AI": "api.featherless.ai",
      Hyperbolic: "api.hyperbolic.xyz",
    },
    "🐳 容器镜像": {
      "Docker Hub": "registry-1.docker.io",
      "Quay.io": "quay.io",
      "Google Container": "gcr.io",
      "Microsoft Container": "mcr.microsoft.com",
      "AWS ECR": "public.ecr.aws",
      "GitHub Container": "ghcr.io",
      "GitLab Container": "registry.gitlab.com",
      "Red Hat": "registry.redhat.io",
      "Oracle Cloud": "container-registry.oracle.com",
      Cloudsmith: "docker.cloudsmith.io",
      DigitalOcean: "registry.digitalocean.com",
      VMware: "projects.registry.vmware.com",
      Kubernetes: "registry.k8s.io",
      Heroku: "registry.heroku.com",
      SUSE: "registry.suse.com",
      openSUSE: "registry.opensuse.org",
      Gitpod: "registry.gitpod.io",
    },
    "🔗 GitHub 资源": {
      "Release 资源": "release-assets.githubusercontent.com",
      "Raw 文件": "raw.githubusercontent.com",
    },
    "🌐 DNS over HTTPS": {
      Cloudflare: "cloudflare-dns.com",
      Google: "dns.google",
      Quad9: "dns.quad9.net",
      NextDNS: "dns.nextdns.io",
      AdGuard: "dns.adguard.com",
      OpenDNS: "doh.opendns.com",
      "阿里 DNS": "dns.alidns.com",
      "DNS.pub": "doh.pub",
      "360 DNS": "doh.360.cn",
      "华为 DNS": "dns.huawei.com",
      Mullvad: "dns.mullvad.net",
      "Control D": "dns.controld.com",
    },
    "📚 其他平台": {
      arXiv: "arxiv.org",
      "F-Droid": "f-droid.org",
      Jenkins: "updates.jenkins.io",
    },
  };

  return categories;
}
